/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as OverzichtIndexRouteImport } from './routes/overzicht/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as DossierIndexRouteImport } from './routes/dossier/index'
import { Route as ActiviteitIndexRouteImport } from './routes/activiteit/index'
import { Route as DossierEditIndexRouteImport } from './routes/dossier/edit/index'
import { Route as DemoTanstackQueryIndexRouteImport } from './routes/demo/tanstack-query/index'
import { Route as DemoTableIndexRouteImport } from './routes/demo/table/index'
import { Route as DemoFormSimpleIndexRouteImport } from './routes/demo/form/simple/index'
import { Route as DemoFormAddressIndexRouteImport } from './routes/demo/form/address/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverzichtIndexRoute = OverzichtIndexRouteImport.update({
  id: '/overzicht/',
  path: '/overzicht/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierIndexRoute = DossierIndexRouteImport.update({
  id: '/dossier/',
  path: '/dossier/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiviteitIndexRoute = ActiviteitIndexRouteImport.update({
  id: '/activiteit/',
  path: '/activiteit/',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierEditIndexRoute = DossierEditIndexRouteImport.update({
  id: '/dossier/edit/',
  path: '/dossier/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryIndexRoute = DemoTanstackQueryIndexRouteImport.update({
  id: '/demo/tanstack-query/',
  path: '/demo/tanstack-query/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableIndexRoute = DemoTableIndexRouteImport.update({
  id: '/demo/table/',
  path: '/demo/table/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleIndexRoute = DemoFormSimpleIndexRouteImport.update({
  id: '/demo/form/simple/',
  path: '/demo/form/simple/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressIndexRoute = DemoFormAddressIndexRouteImport.update({
  id: '/demo/form/address/',
  path: '/demo/form/address/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activiteit': typeof ActiviteitIndexRoute
  '/dossier': typeof DossierIndexRoute
  '/home': typeof HomeIndexRoute
  '/login': typeof LoginIndexRoute
  '/overzicht': typeof OverzichtIndexRoute
  '/signup': typeof SignupIndexRoute
  '/demo/table': typeof DemoTableIndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryIndexRoute
  '/dossier/edit': typeof DossierEditIndexRoute
  '/demo/form/address': typeof DemoFormAddressIndexRoute
  '/demo/form/simple': typeof DemoFormSimpleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activiteit': typeof ActiviteitIndexRoute
  '/dossier': typeof DossierIndexRoute
  '/home': typeof HomeIndexRoute
  '/login': typeof LoginIndexRoute
  '/overzicht': typeof OverzichtIndexRoute
  '/signup': typeof SignupIndexRoute
  '/demo/table': typeof DemoTableIndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryIndexRoute
  '/dossier/edit': typeof DossierEditIndexRoute
  '/demo/form/address': typeof DemoFormAddressIndexRoute
  '/demo/form/simple': typeof DemoFormSimpleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activiteit/': typeof ActiviteitIndexRoute
  '/dossier/': typeof DossierIndexRoute
  '/home/': typeof HomeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/overzicht/': typeof OverzichtIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/demo/table/': typeof DemoTableIndexRoute
  '/demo/tanstack-query/': typeof DemoTanstackQueryIndexRoute
  '/dossier/edit/': typeof DossierEditIndexRoute
  '/demo/form/address/': typeof DemoFormAddressIndexRoute
  '/demo/form/simple/': typeof DemoFormSimpleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activiteit'
    | '/dossier'
    | '/home'
    | '/login'
    | '/overzicht'
    | '/signup'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dossier/edit'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activiteit'
    | '/dossier'
    | '/home'
    | '/login'
    | '/overzicht'
    | '/signup'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/dossier/edit'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/activiteit/'
    | '/dossier/'
    | '/home/'
    | '/login/'
    | '/overzicht/'
    | '/signup/'
    | '/demo/table/'
    | '/demo/tanstack-query/'
    | '/dossier/edit/'
    | '/demo/form/address/'
    | '/demo/form/simple/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiviteitIndexRoute: typeof ActiviteitIndexRoute
  DossierIndexRoute: typeof DossierIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OverzichtIndexRoute: typeof OverzichtIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  DemoTableIndexRoute: typeof DemoTableIndexRoute
  DemoTanstackQueryIndexRoute: typeof DemoTanstackQueryIndexRoute
  DossierEditIndexRoute: typeof DossierEditIndexRoute
  DemoFormAddressIndexRoute: typeof DemoFormAddressIndexRoute
  DemoFormSimpleIndexRoute: typeof DemoFormSimpleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overzicht/': {
      id: '/overzicht/'
      path: '/overzicht'
      fullPath: '/overzicht'
      preLoaderRoute: typeof OverzichtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier/': {
      id: '/dossier/'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof DossierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activiteit/': {
      id: '/activiteit/'
      path: '/activiteit'
      fullPath: '/activiteit'
      preLoaderRoute: typeof ActiviteitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier/edit/': {
      id: '/dossier/edit/'
      path: '/dossier/edit'
      fullPath: '/dossier/edit'
      preLoaderRoute: typeof DossierEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query/': {
      id: '/demo/tanstack-query/'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table/': {
      id: '/demo/table/'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple/': {
      id: '/demo/form/simple/'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address/': {
      id: '/demo/form/address/'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiviteitIndexRoute: ActiviteitIndexRoute,
  DossierIndexRoute: DossierIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OverzichtIndexRoute: OverzichtIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  DemoTableIndexRoute: DemoTableIndexRoute,
  DemoTanstackQueryIndexRoute: DemoTanstackQueryIndexRoute,
  DossierEditIndexRoute: DossierEditIndexRoute,
  DemoFormAddressIndexRoute: DemoFormAddressIndexRoute,
  DemoFormSimpleIndexRoute: DemoFormSimpleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
